return {
	art = {
		colors = { "blue" },
	},
	modules = {
		{ type = "custom", value = "{}", width = "full", fill = "─", color = "gray" },
		{ type = "os", icon = "󰣇", label = "OS", color = "red", format = "{1}" },
		{ type = "kernel", icon = "", label = "Kernel", color = "red" },
		{ type = "packages", icon = "󰏗", color = "green" },
		{ type = "display", icon = "󰍹", color = "green" },
		{ type = "shell", icon = "", label = "Shell", color = "yellow" },
		{ type = "wm", icon = "󱗃", color = "yellow" },
		{ type = "custom", value = "{}", width = "full", fill = "─", color = "gray" },
		{ type = "custom", value = "" },
		{ type = "title", icon = "", format = "{1} @ {2}", color = "white" },
		{ type = "custom", value = "{}", width = "full", fill = "─", color = "gray" },
		{ type = "cpu", icon = "", label = "CPU", color = "blue" },
		{ type = "gpu", icon = "󰊴", color = "blue" },
		{ type = "gpu_driver", icon = "", color = "magenta" },
		{
			type = "memory",
			icon = "",
			label = "Memory",
			color = "magenta",
			format = "{1} of {2} ({3:dynamic})",
			thresholds = { 50.0, 80.0 },
		},
		{
			type = "disk",
			icon = "",
			label = "Storage",
			format = "{1:cyan} / {2:gray} ({3:dynamic})",
			thresholds = { 80.0, 95.0 },
		},
		{ type = "os_age", icon = "󱦟", label = "OS Age", color = "red" },
		{ type = "uptime", icon = "󱫐", label = "Uptime", color = "red" },
		{ type = "custom", value = "{}", width = "full", fill = "─", color = "gray" },
		{ type = "colors" },
	},
}
