return {
	art = {
		colors = { "blue" },
	},
	modules = {
		{ type = "title", icon = "", format = "{1} @ {2}" },
		{ type = "custom", value = "   ┌─────────┐" },
		{ type = "os", label = "OS", separator = "", format = "│ {label:blue}      │ {1}" },
		{ type = "kernel", label = "Kernel", separator = "", format = "│ {label:red}  │ {1}" },
		{ type = "packages", label = "Packs", separator = "", format = "│ {label:red}   │ {1}" },
		{ type = "display", label = "Display", separator = "", format = "│ {label:green} │ {1}" },
		{ type = "shell", label = "Shell", separator = "", format = "│ {label:yellow}   │ {1}" },
		{ type = "wm", label = "WM", separator = "", format = "│ {label:yellow}      │ {1}" },
		{ type = "cpu", label = "CPU", separator = "", format = "│ {label:red}     │ {1}" },
		{ type = "gpu", label = "GPU", separator = "", format = "│ {label:red}     │ {1}" },
		{ type = "gpu_driver", label = "Driver", separator = "", format = "│ {label:red}  │ {1}" },
		{
			type = "memory",
			label = "Mem",
			separator = "",
			format = "│ {label:magenta}     │ {1} / {2} ({3:dynamic})",
			thresholds = { 60, 80 },
		},
		{
			type = "disk",
			label = "Disk",
			separator = "",
			format = "│ {label:magenta}    │ {1} / {2} ({3:dynamic})",
			thresholds = { 60, 80 },
		},
		{ type = "os_age", label = "Age", separator = "", format = "│ {label:blue}     │ {1}" },
		{ type = "uptime", label = "Uptime", separator = "", format = "│ {label:blue}  │ {1}" },
		{ type = "custom", value = "   └─────────┘" },
		{ type = "custom", value = "" },
		{ type = "colors", symbol = "circle" },
	},
}
