source = $HOME/.config/hypr/variables.conf

preload     = $wallpaper
preload     = $wallpaper2

wallpaper {
  monitor = DP-1
  file = $wallpaper
  fit_mode = cover
}

wallpaper {
  monitor = DP-2
  file = $wallpaper2
  fit_mode = cover
}
