
# #### Toolkit Backends ####
env = GDK_BACKEND, wayland,x11
env = QT_QPA_PLATFORM, wayland;xcb
env = SDL_VIDEODRIVER, wayland,x11,windows
env = CLUTTER_BACKEND, wayland
env = ELECTRON_OZONE_PLATFORM_HINT, auto

# #### XDG specifications ####
env = XDG_CURRENT_DESKTOP, Hyprland
env = XDG_SESSION_TYPE, wayland
env = XDG_SESSION_DESKTOP, Hyprland


# #### Cursor ####
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
