### Keyring and auth ###
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

### Interface & background ###
exec-once = hyprpaper &
exec-once = hyprlauncher -d

### Lockscreen utility ###
exec-once = sh ~/.config/hypr/scripts/anitext.sh

### Media Control ###
exec-once = mpris-proxy &

### Aplications ###
exec-once = [workspace special:comm silent] discord &
exec-once = [workspace special:music silent] cider &

