# Example windowrule


windowrule {
  name = "maximize_ignore"
  match:class = .*
  suppress_event = maximize
}

windowrule {
  name = "xwayland-drag-fix"
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
  no_focus = on
}

# Special workspaces

windowrule {
  name = "special_workspace_comm"
  match:class = ^(discord|whatsapp)$
  workspace = special:comm
}

windowrule {
  name = "special_workspace_music"
  match:class = ^(Cider|spotify)$
  workspace = special:music
}

windowrule {
  name = "special_workspace_browser"
  match:class = ^(zen|firefox|chromium)$
  workspace = special:browser
}

# Special visual rules

windowrule {
  name = "opaque"
  match:class = ^(zen|discord|krita)$
  opacity = 1.0 override 1.0 override
}

windowrule {
  name = "imv_style"
  match:class = ^(imv)$
  float = on
  center = on
  size = 800 600
}

# Steam specific

windowrule {
  name = "steam_no_rounding_menus"
  match:class = ^(steam)$
  match:xwayland = 1
  match:float = 1
  match:title = ^$
  rounding = 0
}

windowrule {
  name = "steam_no_rounding_notifications"
  match:class = ^(steam)$
  match:float = 1
  match:title = ^notificationtoasts_[0-9]+_desktop$
  rounding = 0
}

## Even more Steam specific

windowrule {
  name = "tag_games_classes"
  match:class = ^(gamescope|steam_proton|retroarch|steam_app_\d+|HytaleClient)$
  tag = games
}

windowrule {
  name = "tag_games_titles"
  match:title = ^(Minecraft.*)$
  tag = games
}

windowrule {
  name = "tag_games_exe"
  match:class = ^(.*\.exe)$
  match:title = ^(.+)$
  tag = games
}

windowrule {
  name = "apply_games_rules"
  match:tag = games
  workspace = 5
  no_blur = on
  fullscreen = on
}


# Related to an app I'm building localy (can be ignored or deleted)

windowrule {
  name = "torigen_opaque"
  match:class = ^(torigen)$
  opacity = 1.0 override 1.0 override
}
