# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Special workspaces
windowrulev2 = workspace special comm, class:discord|whatsapp
windowrulev2 = workspace special music, class:Cider|spotify
windowrulev2 = workspace special browser, class:^(zen|firefox|chromium)$

# Special visual rules
windowrulev2 = opaque, class:^(zen)$
